[package]
name = "solanaproj"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5"
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-sdk = "2.3.1"
tokio = { version = "1.45.1", features = ["full"] }
